### ISSUE TITLE
open codes

### ISSUE THREAD

**Issue by HanAccount** [HHHZM/SC-EGG#1]
Dear author:
When will the thesis code be made public?
Can the visualization code be published together?

**Comment by HHHZM** [comment]
@HanAccount Sorry for the delay, I will update the codes in this month! You can refer the visualization code (attention map) in https://github.com/hbdat/cvpr20_DAZLE/blob/e5a04601d8368903008fd96dee3d95dde398aa51/core/helper_func.py#L365
